server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: config-server
          uri: https://github.com/braBarla/microservices-project1
          search-path: config-data
  application:
    name: config-service